version: "3.7"
services:
    app:
        build:
            context: ./
            dockerfile: build/app/Dockerfile
            args:
                - DEBUG=1
                - HOST_USER_NAME=mylk
                - HOST_USER_ID=1000
                - HOST_GROUP_ID=1000
        ports:
            - "8000:8000"
        networks:
            - ojah_net
        volumes:
            - ./:/ojah
        depends_on: [rabbitmq]
        environment:
            - DEBUG=1
        cap_add:
            - NET_ADMIN
    worker_classify:
        build:
            context: ./
            dockerfile: build/worker_classify/Dockerfile
            args:
                - HOST_USER_NAME=mylk
                - HOST_USER_ID=1000
                - HOST_GROUP_ID=1000
        networks:
            - ojah_net
        volumes:
            - ./:/ojah
        depends_on: [rabbitmq]
    rabbitmq:
        image: rabbitmq:3-management
        networks:
            - ojah_net
networks:
    ojah_net:
        driver: "bridge"
