version: "3.7"

x-base: &base
    depends_on: [mariadb, rabbitmq]
    env_file:
        - './build/mariadb.env'
    environment:
        - DEBUG=0
    networks:
        - ojah_net
    volumes:
        - ./:/ojah

services:
    app:
        <<: *base
        build:
            context: ./
            dockerfile: build/app/Dockerfile
            args:
                - DEBUG=1
                - HOST_USER_NAME=mylk
                - HOST_USER_ID=1000
                - HOST_GROUP_ID=1000
        hostname: app
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
        cap_add:
            - NET_ADMIN

    crawler:
        <<: *base
        build:
            context: ./
            dockerfile: build/crawler/Dockerfile
            args:
                - DEBUG=0
                - HOST_USER_NAME=mylk
                - HOST_USER_ID=1000
                - HOST_GROUP_ID=1000
        hostname: crawler

    classifier:
        <<: *base
        build:
            context: ./
            dockerfile: build/classifier/Dockerfile
            args:
                - DEBUG=0
                - HOST_USER_NAME=mylk
                - HOST_USER_ID=1000
                - HOST_GROUP_ID=1000
        hostname: classifier

    test:
        <<: *base
        build:
            context: ./
            dockerfile: build/test/Dockerfile
            args:
                - HOST_USER_NAME=mylk
                - HOST_USER_ID=1000
                - HOST_GROUP_ID=1000
        hostname: test

    rabbitmq:
        image: rabbitmq:3-management
        hostname: rabbitmq
        networks:
            - ojah_net

    mariadb:
        <<: *base
        build:
            context: ./
            dockerfile: build/mariadb/Dockerfile
            args:
                - HOST_USER_NAME=mylk
                - HOST_USER_ID=1000
                - HOST_GROUP_ID=1000
        hostname: mariadb
        depends_on: []
        volumes:
            - ./data/mariadb/data:/var/lib/mysql
            - ./data/mariadb/init:/docker-entrypoint-initdb.d/:ro

networks:
    ojah_net:
        driver: "bridge"
