# Generated by Django 2.0.7 on 2018-07-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_auto_20180720_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
