# Generated by Django 2.0.13 on 2019-05-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190104_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
