# Generated by Django 3.0.5 on 2020-04-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200415_0014'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER DATABASE ojah CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE news_item CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
            """
        )
    ]
