# Generated by Django 3.1.3 on 2020-11-24 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_source_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_total', models.SmallIntegerField(null=True)),
                ('news_items_count', models.PositiveIntegerField(null=True)),
                ('corpora_count', models.IntegerField(null=True)),
                ('sources_count', models.SmallIntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'statistics',
            },
        ),
    ]
