# Generated by Django 3.1.3 on 2020-12-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_corpus_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='pending_classify_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
