# Generated by Django 2.0.7 on 2018-07-20 08:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rss', '0000_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
                ),
                ('positive', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'corpus',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
                ),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField(null=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'news_item',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
                ),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('last_crawl', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'source',
            },
        ),
        migrations.AddField(
            model_name='newsitem',
            name='source',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rss.Source'
            ),
        ),
        migrations.AddField(
            model_name='corpus',
            name='news_item',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to='rss.NewsItem'
            ),
        ),
    ]
