# Generated by Django 2.0.7 on 2018-09-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_newsitem_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpus',
            options={'verbose_name': 'corpus', 'verbose_name_plural': 'corpora'},
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
