# Generated by Django 2.0.7 on 2018-09-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_auto_20180917_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
