# Generated by Django 2.0.8 on 2019-01-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0004_auto_20180917_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusMetric',
            fields=[
            ],
            options={
                'verbose_name': 'corpus metric',
                'verbose_name_plural': 'corpus metrics',
                'proxy': True,
                'indexes': [],
            },
            bases=('rss.corpus',),
        ),
        migrations.CreateModel(
            name='NewsItemMetric',
            fields=[
            ],
            options={
                'verbose_name': 'news item metric',
                'verbose_name_plural': 'news item metrics',
                'proxy': True,
                'indexes': [],
            },
            bases=('rss.newsitem',),
        ),
        migrations.AddField(
            model_name='source',
            name='homepage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
